# -*- coding: utf-8 -*-
"""BinaryCepheidGifBetterVisualforWebsite.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-eiNXRnMPRprB542A6HylTQ1_6bIr8ie
"""

!pip install astroquery
!pip install astropy

!apt-get install ffmpeg

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from dataclasses import dataclass
from astropy.coordinates import SkyCoord
import astropy.units as u

# ==========================================
# PHASE 0: CONFIGURATION & CONSTANTS
# ==========================================

# --- 1. GLOBAL PHYSICS CONSTANTS (Invariant) ---
# Keeping these separate ensures accidental overwrites don't break physics calculations.
class Physics:
    G = 6.674e-11 * u.m**3 / (u.kg * u.s**2)
    M_SUN = 1.989e30 * u.kg
    R_SUN = 6.957e8 * u.m
    DAY_SEC = 86400 * u.s
    SIGMA_CLIP = 3  # Outlier rejection threshold (sigma units, used in clean_outliers_phased)

# --- 2. TARGET CONFIGURATION FRAMEWORK ---
@dataclass
class TargetConfig:
    """
    A template for target parameters.
    Fill this out for any new star to ensure the pipeline runs correctly.
    """
    name: str
    coords: SkyCoord

    # Periods (Days)
    p_puls: float      # First Overtone
    p_puls_2: float    # Second Overtone
    p_orb: float       # Orbital Period
    t0_orb: float      # Reference Epoch (HJD)

    # Physical Properties (Solar Units)
    m1: float          # Mass Cepheid
    m2: float          # Mass Companion
    r1: float          # Radius Cepheid
    r2: float          # Radius Companion

    # Temperatures (Kelvin)
    teff1: float
    teff2: float
    dist_pc: float     # Distance in Parsecs
    inclination_deg: float = 57.0  # Orbital inclination (degrees); inferred from evolutionary masses

    def summary(self):
        """Prints a standardized summary of the loaded configuration."""
        q = self.m2 / self.m1
        print(f"✅ Configuration Loaded for {self.name}")
        print(f"   • Coordinates:   {self.coords.to_string('hmsdms')}")
        print(f"   • Cepheid Mass:  {self.m1} M_sun")
        print(f"   • Companion Mass:{self.m2} M_sun (q = {q:.2f})")
        print(f"   • Cepheid Radius:{self.r1} R_sun")
        print(f"   • Orbital Period:{self.p_orb} days")

# --- 3. LOAD TARGET DATA ---
# To switch targets in the future, simply copy this block and change values.
current_target = TargetConfig(
    name="OGLE-LMC-CEP-1347",
    coords=SkyCoord('05 15 06.4', '-69 39 05.3', unit=(u.hourangle, u.deg), frame='icrs'),

    p_puls=0.69001,
    p_puls_2=0.556,
    p_orb=58.85,
    t0_orb=2459000.0,

    m1=3.41,
    m2=1.89,
    r1=13.65,
    r2=12.51,

    teff1=6490,
    teff2=4910,
    dist_pc=49800
)

# --- 4. EXECUTION ---
current_target.summary()

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from astropy.time import Time
from astropy.coordinates import SkyCoord, EarthLocation
import astropy.units as u

def set_pub_style():
    sns.set_theme(style="ticks", context="paper")
    plt.rcParams.update({
        "font.family": "serif",
        "font.serif": ["Times New Roman", "DejaVu Serif"],
        "mathtext.fontset": "stix",
        "axes.labelsize": 14,
        "axes.titlesize": 14,
        "xtick.labelsize": 12,
        "ytick.labelsize": 12,
        "xtick.direction": "in",
        "ytick.direction": "in",
        "lines.linewidth": 1.5,
        "figure.dpi": 300
    })

set_pub_style()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from astropy.time import Time
from astropy.coordinates import EarthLocation

# ==========================================
# ROBUST CLEANING FUNCTION
# ==========================================

def clean_outliers_phased(df, period, sigma=3.0, bins=50):
    """
    Removes outliers using Median Absolute Deviation (MAD).
    MAD is resistant to outliers, unlike Standard Deviation.
    """
    if df is None or len(df) == 0:
        return df

    df_work = df.copy()

    # 1. Calculate Phase
    df_work['Temp_Phase'] = (df_work['BJD'] % period) / period

    # 2. Bin the data
    df_work['Bin_ID'] = pd.cut(df_work['Temp_Phase'], bins=bins)

    # 3. Calculate Local Median
    # The 'center' of the data in this bin
    local_median = df_work.groupby('Bin_ID')['Mag'].transform('median')

    # 4. Calculate MAD (Median Absolute Deviation)
    # How far is each point from the median?
    df_work['Abs_Diff'] = np.abs(df_work['Mag'] - local_median)
    # What is the median of those distances?
    local_mad = df_work.groupby('Bin_ID')['Abs_Diff'].transform('median')

    # Scale MAD to approximate Sigma (Standard Normal Distribution)
    # Sigma approx = 1.4826 * MAD
    local_sigma_robust = local_mad * 1.4826

    # 5. Create Threshold
    # We still respect the reported error bars as a minimum floor
    # If the scatter is smaller than the error bars, use the error bars.
    min_floor = 3 * df_work['Err'].median()
    threshold = np.maximum(sigma * local_sigma_robust, min_floor)

    # 6. Apply Mask
    mask = df_work['Abs_Diff'] < threshold

    # Debugging: Print how tight the clipping is
    # avg_thresh = threshold.mean()
    # print(f"      [Debug] Average Clipping Threshold: +/- {avg_thresh:.3f} mag")

    return df[mask].reset_index(drop=True)

# ==========================================
# MAIN LOADING PIPELINE
# ==========================================

def fetch_and_clean_multiband(target_config, bands=['I', 'V']):
    observatory = EarthLocation.of_site('Las Campanas Observatory')
    base_url = "https://www.astrouw.edu.pl/ogle/ogle4/OCVS/lmc/cep/phot"

    data_store = {}
    print(f"🚀 Processing Data for {target_config.name}")

    for band in bands:
        url = f"{base_url}/{band}/{target_config.name}.dat"
        try:
            # --- 1. FETCH ---
            df = pd.read_csv(url, delim_whitespace=True, names=['HJD_Raw', 'Mag', 'Err'], comment='#')
            raw_count = len(df)

            # --- 2. TIME & PHYSICS CORRECTION ---
            if df['HJD_Raw'].mean() < 2400000:
                df['HJD_UTC'] = df['HJD_Raw'] + 2450000.0
            else:
                df['HJD_UTC'] = df['HJD_Raw']

            t = Time(df['HJD_UTC'], format='jd', scale='utc', location=observatory)
            ltt = t.light_travel_time(target_config.coords)
            df['BJD'] = t.tdb.jd + ltt.value

            # --- 3. BASIC CLEANING (Error bars) ---
            # Remove garbage points with massive error bars first
            df = df[df['Err'] < 3 * df['Err'].mean()]

            # --- 4. ADVANCED CLEANING (Phased Sigma Clipping) ---
            # This is the new part that fixes your issue
            df_clean = clean_outliers_phased(df, target_config.p_puls, sigma=Physics.SIGMA_CLIP)

            data_store[band] = df_clean.reset_index(drop=True)
            print(f"   ✅ {band}-band: {len(df_clean)}/{raw_count} epochs retained (Removed {raw_count - len(df_clean)} outliers)")

        except Exception as e:
            print(f"   ❌ Error {band}-band: {e}")
            data_store[band] = None

    return data_store

def plot_diagnostics(data_dict, target_config):
    """Visual confirmation of the cleaning"""
    fig, axes = plt.subplots(1, 2, figsize=(12, 5))

    for band, color in [('I', 'r'), ('V', 'g')]:
        if data_dict.get(band) is not None:
            df = data_dict[band]

            # Phased Plot
            phase = (df['BJD'] % target_config.p_puls) / target_config.p_puls
            axes[0].errorbar(phase, df['Mag'], yerr=df['Err'], fmt='.', color=color, alpha=0.4, label=f'{band}')

            # Raw Time Series
            axes[1].errorbar(df['BJD'], df['Mag'], yerr=df['Err'], fmt='.', color=color, alpha=0.4)

    axes[0].invert_yaxis()
    axes[0].set_title("Phased Light Curve (Cleaned)")
    axes[0].set_xlabel("Phase")

    axes[1].invert_yaxis()
    axes[1].set_title("Time Series (BJD)")
    axes[1].set_xlabel("Date (BJD)")

    plt.legend()
    plt.show()

# ==========================================
# EXECUTION
# ==========================================
# Assumes 'current_target' is defined from Phase 0
lc_data = fetch_and_clean_multiband(current_target)
plot_diagnostics(lc_data, current_target)

df_i = lc_data['I']
df_v = lc_data['V']

import matplotlib.animation as animation
from matplotlib.patches import Circle
import math

# ==========================================
# PHASE 1: KINEMATICS & ANIMATION
# ==========================================

def calculate_orbital_elements(target):
    """Calculates orbital separation (a) in Solar Radii using Kepler's 3rd Law."""
    P_sec = target.p_orb * Physics.DAY_SEC.value
    M_total_kg = (target.m1 + target.m2) * Physics.M_SUN.value

    # Kepler's 3rd law: a^3 = G * M * P^2 / (4 * pi^2)
    a_cubed = (Physics.G.value * M_total_kg * P_sec**2) / (4 * math.pi**2)
    a_meters = a_cubed**(1/3)
    a_rsun = a_meters / Physics.R_SUN.value

    # Distances from barycenter
    a1 = a_rsun * (target.m2 / (target.m1 + target.m2))
    a2 = a_rsun * (target.m1 / (target.m1 + target.m2))

    return a_rsun, a1, a2

def generate_binary_cepheid_gif(target, filename="cepheid_binary.gif", duration_days=None, fps=24):
    print(f"🎬 Initializing Animation for {target.name}...")

    a_tot, a1, a2 = calculate_orbital_elements(target)
    print(f"   • Orbital Separation: {a_tot:.2f} R_sun")

    # Setup Figure
    fig, ax = plt.subplots(figsize=(8, 8), facecolor='black')
    ax.set_facecolor('black')

    # Plot limits based on separation
    lim = a_tot * 1.2
    ax.set_xlim(-lim, lim)
    ax.set_ylim(-lim, lim)
    ax.set_aspect('equal')
    ax.axis('off') # Hide axes for cinematic look

    # Draw orbit trails (circular assumption)
    orbit1 = Circle((0, 0), a1, color='white', fill=False, linestyle=':', alpha=0.3)
    orbit2 = Circle((0, 0), a2, color='white', fill=False, linestyle=':', alpha=0.3)
    ax.add_patch(orbit1)
    ax.add_patch(orbit2)

    # Draw Barycenter
    ax.plot(0, 0, marker='+', color='white', markersize=10, alpha=0.5)

    # Initialize Stars (Using simplified colors based on Teff)
    # Cepheid (Yellow-White), Companion (Red-Orange)
    star1 = Circle((a1, 0), target.r1, color='#FFD700', zorder=10)
    star2 = Circle((-a2, 0), target.r2, color='#FF8C00', zorder=10)
    ax.add_patch(star1)
    ax.add_patch(star2)

    # Title overlay
    title_text = ax.text(0.5, 0.95, f"{target.name} System\nTime: 0.00 Days",
                         color='white', ha='center', va='top',
                         transform=ax.transAxes, fontsize=14, fontfamily='monospace')

    # Animation parameters
    if duration_days is None:
        duration_days = target.p_orb  # Animate one full orbit by default

    frames = int(fps * (duration_days / (target.p_orb / 10))) # Number of frames
    time_step = duration_days / frames

    # The pulsation amplitude visually (fraction of radius).
    # In reality this is ~5-15%, we use 15% to make it visible.
    pulsation_amplitude = 0.15

    def update(frame):
        t = frame * time_step

        # 1. Update Orbital Positions (Angles)
        theta_orb = 2 * math.pi * (t / target.p_orb)

        # Star 1 (Cepheid)
        x1 = a1 * math.cos(theta_orb)
        y1 = a1 * math.sin(theta_orb)
        star1.center = (x1, y1)

        # Star 2 (Companion is 180 degrees offset)
        x2 = a2 * math.cos(theta_orb + math.pi)
        y2 = a2 * math.sin(theta_orb + math.pi)
        star2.center = (x2, y2)

        # 2. Update Cepheid Radius (Pulsation)
        # Using a simple sine wave; you could link this to an interpolated function from df_v
        phase_puls = 2 * math.pi * (t / target.p_puls)
        current_r1 = target.r1 * (1 + pulsation_amplitude * math.sin(phase_puls))
        star1.radius = current_r1

        # 3. Update Text
        title_text.set_text(f"{target.name} System\nTime: {t:.2f} Days")

        return star1, star2, title_text

    print("   ⏳ Rendering frames (this may take a minute)...")
    anim = animation.FuncAnimation(fig, update, frames=frames, interval=1000/fps, blit=True)

    # Save as GIF
    anim.save(filename, writer='pillow', fps=fps)
    print(f"✅ Animation saved to {filename}")
    plt.close()

# ==========================================
# EXECUTE ANIMATION
# ==========================================
#generate_binary_cepheid_gif(current_target, filename="cepheid_binary.gif", duration_days=current_target.p_orb, fps=30)

from scipy.optimize import curve_fit

# ==========================================
# PHASE 2: LIGHT CURVE TEMPLATE FITTING
# ==========================================

def fourier_series(phase, a0, *args):
    """
    Mathematical model for the Cepheid light curve.
    args expects pairs of (a_k, b_k) for each harmonic.
    """
    result = a0
    n_harmonics = len(args) // 2
    for k in range(1, n_harmonics + 1):
        ak = args[2*(k-1)]
        bk = args[2*(k-1) + 1]
        result += ak * np.cos(2 * np.pi * k * phase) + bk * np.sin(2 * np.pi * k * phase)
    return result

def fit_cepheid_template(df, period, n_harmonics=4, band_name="Band"):
    """Fits a Fourier series to the phased light curve data."""
    print(f"📈 Fitting {n_harmonics}-harmonic Fourier template for {band_name}...")

    # 1. Calculate phase for the data
    phase = (df['BJD'] % period) / period

    # 2. Setup initial guesses: [Mean Mag, a1, b1, a2, b2, ...]
    # We guess 0.0 for the amplitude components to start
    p0 = [df['Mag'].mean()] + [0.0, 0.0] * n_harmonics

    # 3. Perform the least-squares fit, weighting by photometric errors
    try:
        popt, pcov = curve_fit(
            fourier_series,
            phase,
            df['Mag'],
            p0=p0,
            sigma=df['Err'],
            absolute_sigma=True
        )
        print(f"   ✅ Fit successful! Mean Magnitude (A0): {popt[0]:.3f}")
        return popt
    except RuntimeError:
        print(f"   ❌ Fit failed to converge for {band_name}.")
        return None

def plot_fitted_template(df, popt, period, band_name, color):
    """Visualizes the data overlaid with the continuous mathematical template."""
    phase = (df['BJD'] % period) / period

    # Create a smooth array of phases from 0 to 1 for the template line
    smooth_phase = np.linspace(0, 1, 500)
    smooth_mag = fourier_series(smooth_phase, *popt)

    plt.figure(figsize=(8, 5))
    # Plot raw data
    plt.errorbar(phase, df['Mag'], yerr=df['Err'], fmt='.', color=color, alpha=0.3, label='OGLE Data')
    # Double the phase (0 to 2) to show the cycle repeating
    plt.errorbar(phase + 1.0, df['Mag'], yerr=df['Err'], fmt='.', color=color, alpha=0.3)

    # Plot smooth template
    plt.plot(smooth_phase, smooth_mag, color='black', linewidth=2, label=f'Fourier Fit (N={len(popt)//2})')
    plt.plot(smooth_phase + 1.0, smooth_mag, color='black', linewidth=2)

    plt.gca().invert_yaxis()
    plt.title(f"{current_target.name} - {band_name} Band Template Fit")
    plt.xlabel("Pulsation Phase")
    plt.ylabel("Magnitude")
    plt.legend()
    plt.tight_layout()
    plt.show()

# ==========================================
# EXECUTION
# ==========================================
# Fit the I-band and V-band
popt_i = fit_cepheid_template(df_i, current_target.p_puls, n_harmonics=5, band_name='I')
popt_v = fit_cepheid_template(df_v, current_target.p_puls, n_harmonics=5, band_name='V')

# Plot the V-band to verify the fit looks good
#if popt_v is not None:
    #plot_fitted_template(df_v, popt_v, current_target.p_puls, 'V', 'green')

from scipy.optimize import curve_fit

# ==========================================
# PHASE 2: LIGHT CURVE TEMPLATE FITTING
# ==========================================

def fourier_series(phase, a0, *args):
    """
    Mathematical model for the Cepheid light curve.
    args expects pairs of (a_k, b_k) for each harmonic.
    """
    result = a0
    n_harmonics = len(args) // 2
    for k in range(1, n_harmonics + 1):
        ak = args[2*(k-1)]
        bk = args[2*(k-1) + 1]
        result += ak * np.cos(2 * np.pi * k * phase) + bk * np.sin(2 * np.pi * k * phase)
    return result

def fit_cepheid_template(df, period, n_harmonics=4, band_name="Band"):
    """Fits a Fourier series to the phased light curve data."""
    print(f"📈 Fitting {n_harmonics}-harmonic Fourier template for {band_name}...")

    # 1. Calculate phase for the data
    phase = (df['BJD'] % period) / period

    # 2. Setup initial guesses: [Mean Mag, a1, b1, a2, b2, ...]
    # We guess 0.0 for the amplitude components to start
    p0 = [df['Mag'].mean()] + [0.0, 0.0] * n_harmonics

    # 3. Perform the least-squares fit, weighting by photometric errors
    try:
        popt, pcov = curve_fit(
            fourier_series,
            phase,
            df['Mag'],
            p0=p0,
            sigma=df['Err'],
            absolute_sigma=True
        )
        print(f"   ✅ Fit successful! Mean Magnitude (A0): {popt[0]:.3f}")
        return popt
    except RuntimeError:
        print(f"   ❌ Fit failed to converge for {band_name}.")
        return None

def plot_fitted_template(df, popt, period, band_name, color):
    """Visualizes the data overlaid with the continuous mathematical template."""
    phase = (df['BJD'] % period) / period

    # Create a smooth array of phases from 0 to 1 for the template line
    smooth_phase = np.linspace(0, 1, 500)
    smooth_mag = fourier_series(smooth_phase, *popt)

    plt.figure(figsize=(8, 5))
    # Plot raw data
    plt.errorbar(phase, df['Mag'], yerr=df['Err'], fmt='.', color=color, alpha=0.3, label='OGLE Data')
    # Double the phase (0 to 2) to show the cycle repeating
    plt.errorbar(phase + 1.0, df['Mag'], yerr=df['Err'], fmt='.', color=color, alpha=0.3)

    # Plot smooth template
    plt.plot(smooth_phase, smooth_mag, color='black', linewidth=2, label=f'Fourier Fit (N={len(popt)//2})')
    plt.plot(smooth_phase + 1.0, smooth_mag, color='black', linewidth=2)

    plt.gca().invert_yaxis()
    plt.title(f"{current_target.name} - {band_name} Band Template Fit")
    plt.xlabel("Pulsation Phase")
    plt.ylabel("Magnitude")
    plt.legend()
    plt.tight_layout()
    plt.show()

# ==========================================
# EXECUTION
# ==========================================
# Fit the I-band and V-band
popt_i = fit_cepheid_template(df_i, current_target.p_puls, n_harmonics=5, band_name='I')
popt_v = fit_cepheid_template(df_v, current_target.p_puls, n_harmonics=5, band_name='V')

# Plot the V-band to verify the fit looks good
if popt_v is not None:
    plot_fitted_template(df_v, popt_v, current_target.p_puls, 'V', 'green')

# Plot the V-band to verify the fit looks good
if popt_i is not None:
    plot_fitted_template(df_i, popt_i, current_target.p_puls, 'I', 'red')

import matplotlib.animation as animation
from matplotlib.patches import Circle, Ellipse
import matplotlib.colors as mcolors
import numpy as np

# ==========================================
# PHASE 3: DATA-DRIVEN ANIMATION
# ==========================================

def teff_to_hex(teff):
    """
    Approximates the visible RGB color of a star based on its temperature.
    Uses a simplified blackbody color mapping.
    """
    # Clip temperature to valid visualization range
    t = max(3000, min(teff, 10000))

    # Normalize temperature to a 0-1 scale between 4000K (Orange) and 8000K (White/Blue-white)
    norm = (t - 4000) / (8000 - 4000)
    norm = max(0, min(norm, 1))

    # Interpolate between an orange-red and a hot white
    c_cool = np.array(mcolors.to_rgb('#ff8c00')) # 4000K
    c_hot = np.array(mcolors.to_rgb('#f4f6ff'))  # 8000K

    c_current = c_cool + norm * (c_hot - c_cool)
    return mcolors.to_hex(c_current)

def vi_index_to_teff(v_minus_i):
    """
    Empirical approximation converting (V-I) color index to Teff for Cepheids.
    Consistent with CepheidSimulator.vi_to_teff: 9500 - 5000*(V-I).
    Yields ~7000K at V-I=0.5, ~4500K at V-I=1.0.
    """
    return 9500 - 5000 * v_minus_i

def generate_data_driven_gif(target, popt_v, popt_i, filename="cepheid_binary.gif", duration_days=None, fps=24):
    print(f"🎬 Initializing Data-Driven Animation for {target.name}...")

    # 1. Orbital Setup
    a_tot, a1, a2 = calculate_orbital_elements(target)
    inclination_rad = np.radians(target.inclination_deg)
    ax.set_facecolor('black')

    lim = a_tot * 1.2
    ax.set_xlim(-lim, lim)
    ax.set_ylim(-lim, lim)
    ax.set_aspect('equal')
    ax.axis('off')

    # Draw Inclined Orbit Trails
    # An inclined circular orbit appears as an ellipse with height scaled by cos(i)
    orbit1 = Ellipse((0, 0), width=a1*2, height=a1*2*np.cos(inclination_rad),
                     color='white', fill=False, linestyle=':', alpha=0.3)
    orbit2 = Ellipse((0, 0), width=a2*2, height=a2*2*np.cos(inclination_rad),
                     color='white', fill=False, linestyle=':', alpha=0.3)
    ax.add_patch(orbit1)
    ax.add_patch(orbit2)
    ax.plot(0, 0, marker='+', color='white', markersize=10, alpha=0.5) # Barycenter

    # 3. Initialize Stars
    companion_color = teff_to_hex(target.teff2)
    star2 = Circle((0, 0), target.r2, color=companion_color, zorder=10)
    star1 = Circle((0, 0), target.r1, color='#ffffff', zorder=11) # Color will update dynamically
    ax.add_patch(star2)
    ax.add_patch(star1)

    # Info Overlay
    info_text = ax.text(0.05, 0.95, "", color='white', ha='left', va='top',
                        transform=ax.transAxes, fontsize=12, fontfamily='monospace')

    # Animation Time Settings
    if duration_days is None:
        duration_days = target.p_orb
    frames = int(fps * duration_days)
    time_step = 1.0 / fps # 1 day per second in the animation

    # Extract mean magnitude to calculate relative radius changes
    mean_mag_v = popt_v[0]
    # For a rough visual, a 0.5 mag amplitude might correspond to a ~10-15% radius change
    radius_scale_factor = target.r1 * 0.2

    def update(frame):
        t = frame * time_step

        # --- ORBITAL KINEMATICS ---
        theta = 2 * np.pi * (t / target.p_orb)

        # Apply inclination to the y-axis
        x1 = a1 * np.cos(theta)
        y1 = a1 * np.sin(theta) * np.cos(inclination_rad)
        star1.center = (x1, y1)

        x2 = a2 * np.cos(theta + np.pi)
        y2 = a2 * np.sin(theta + np.pi) * np.cos(inclination_rad)
        star2.center = (x2, y2)

        # Add a pseudo-3D z-ordering based on the y-position before inclination
        y1_true = a1 * np.sin(theta)
        if y1_true > 0:
            star1.set_zorder(9)
            star2.set_zorder(11)
        else:
            star1.set_zorder(11)
            star2.set_zorder(9)

        # --- PHOTOMETRY, COLOR, & RADIUS ---
        phase_puls = (t % target.p_puls) / target.p_puls

        # Calculate instantaneous magnitudes using our Fourier fits
        mag_v = fourier_series(phase_puls, *popt_v)
        mag_i = fourier_series(phase_puls, *popt_i)

        # Color Index to Temperature to Hex Color
        v_minus_i = mag_v - mag_i
        current_teff = vi_index_to_teff(v_minus_i)
        star1.set_color(teff_to_hex(current_teff))

        # Magnitude to Radius (Brighter = negative magnitude delta = larger radius in this visual)
        # Note: In real Cepheids, max brightness happens near minimum radius, but we'll
        # invert the magnitude curve to visually represent the pulsation pressure wave.
        delta_mag = mean_mag_v - mag_v
        current_r1 = target.r1 + (delta_mag * radius_scale_factor)
        star1.radius = current_r1

        # --- UPDATE TEXT ---
        info_str = (
            f"Time: {t:.1f} d\n"
            f"Puls Phase: {phase_puls:.2f}\n"
            f"V-Mag: {mag_v:.2f}\n"
            f"(V-I): {v_minus_i:.2f}\n"
            f"T_eff: ~{current_teff:.0f}K"
        )
        info_text.set_text(info_str)

        return star1, star2, info_text, orbit1, orbit2

    print(f"   ⏳ Rendering {frames} frames...")
    anim = animation.FuncAnimation(fig, update, frames=frames, interval=1000/fps, blit=True)
    anim.save(filename, writer='pillow', fps=fps)
    print(f"✅ Saved visually accurate data-driven animation to {filename}!")
    plt.close()

# ==========================================
# EXECUTE DATA-DRIVEN ANIMATION
# ==========================================
# Ensure popt_v and popt_i were successfully generated in Phase 2
#if popt_v is not None and popt_i is not None:
    #generate_data_driven_gif(current_target, popt_v, popt_i, filename="cepheid_inclined_data.gif", duration_days=current_target.p_orb, fps=15)

import matplotlib.animation as animation
from matplotlib.patches import Circle, Ellipse
import matplotlib.colors as mcolors
import numpy as np
import matplotlib.pyplot as plt

# ==========================================
# PHASE 3: DATA-DRIVEN ANIMATION (LOW-RAM VIDEO VERSION)
# ==========================================

def generate_data_driven_video(target, popt_v, popt_i, filename="cepheid_binary.mp4", duration_days=None, fps=30):
    print(f"🎬 Initializing Low-RAM Data-Driven Video for {target.name}...")

    # 1. Orbital Setup
    a_tot, a1, a2 = calculate_orbital_elements(target)
    inclination_rad = np.radians(target.inclination_deg)

    # THE RAM FIX: Explicitly lower DPI to web-standard (100)
    fig, ax = plt.subplots(figsize=(8, 8), facecolor='black', dpi=100)
    fig.patch.set_facecolor('black')

    # Explicit plot limits (Fixed to 150 R_sun for stability)
    lim = 150
    ax.set_xlim(-lim, lim)
    ax.set_ylim(-lim, lim)
    ax.set_aspect('equal')
    ax.axis('off')

    # Draw Inclined Orbit Trails
    orbit1 = Ellipse((0, 0), width=a1*2, height=a1*2*np.cos(inclination_rad),
                     color='white', fill=False, linestyle=':', alpha=0.3)
    orbit2 = Ellipse((0, 0), width=a2*2, height=a2*2*np.cos(inclination_rad),
                     color='white', fill=False, linestyle=':', alpha=0.3)
    ax.add_patch(orbit1)
    ax.add_patch(orbit2)
    ax.plot(0, 0, marker='+', color='white', markersize=10, alpha=0.5)

    # 3. Initialize Stars
    companion_color = teff_to_hex(target.teff2)
    star2 = Circle((0, 0), target.r2, color=companion_color, zorder=10)
    star1 = Circle((0, 0), target.r1, color='#ffffff', zorder=11)
    ax.add_patch(star2)
    ax.add_patch(star1)

    # Info Overlay
    info_text = ax.text(0.05, 0.95, "", color='white', ha='left', va='top',
                        transform=ax.transAxes, fontsize=12, fontfamily='monospace')

    # Animation Time Settings
    if duration_days is None:
        duration_days = target.p_orb
    frames = int(fps * duration_days)
    time_step = 1.0 / fps

    mean_mag_v = popt_v[0]
    radius_scale_factor = target.r1 * 0.2

    def update(frame):
        t = frame * time_step

        # --- ORBITAL KINEMATICS ---
        theta = 2 * np.pi * (t / target.p_orb)

        x1 = a1 * np.cos(theta)
        y1 = a1 * np.sin(theta) * np.cos(inclination_rad)
        star1.center = (x1, y1)

        x2 = a2 * np.cos(theta + np.pi)
        y2 = a2 * np.sin(theta + np.pi) * np.cos(inclination_rad)
        star2.center = (x2, y2)

        y1_true = a1 * np.sin(theta)
        if y1_true > 0:
            star1.set_zorder(9)
            star2.set_zorder(11)
        else:
            star1.set_zorder(11)
            star2.set_zorder(9)

        # --- PHOTOMETRY, COLOR, & RADIUS ---
        phase_puls = (t % target.p_puls) / target.p_puls

        mag_v = fourier_series(phase_puls, *popt_v)
        mag_i = fourier_series(phase_puls, *popt_i)

        v_minus_i = mag_v - mag_i
        current_teff = vi_index_to_teff(v_minus_i)
        star1.set_color(teff_to_hex(current_teff))

        delta_mag = mean_mag_v - mag_v
        current_r1 = target.r1 + (delta_mag * radius_scale_factor)
        star1.radius = current_r1

        # --- UPDATE TEXT ---
        info_str = (
            f"Time: {t:.1f} d\n"
            f"Puls Phase: {phase_puls:.2f}\n"
            f"V-Mag: {mag_v:.2f}\n"
            f"(V-I): {v_minus_i:.2f}\n"
            f"T_eff: ~{current_teff:.0f}K"
        )
        info_text.set_text(info_str)

        return star1, star2, info_text, orbit1, orbit2

    print(f"   ⏳ Streaming {frames} frames directly to disk via FFmpeg...")
    anim = animation.FuncAnimation(fig, update, frames=frames, interval=1000/fps, blit=True)

    # THE RAM FIX: FFmpeg streams directly to disk
    writer = animation.FFMpegWriter(fps=fps, bitrate=1800)
    anim.save(filename, writer=writer)

    print(f"✅ Saved visually accurate data-driven video to {filename}!")

    # THE RAM FIX: Explicitly close the figure to flush memory
    plt.close(fig)

"""# Documentation: `master_data.json`

The exported JSON file contains all the pre-calculated physics and animation data required to render the Cepheid binary system in a web frontend. It is structured into three main sections.

### 1. `metadata`
Global constants and configuration parameters for the system.

| Key | Type | Description |
| :--- | :--- | :--- |
| `name` | String | Name of the target (e.g., "OGLE-LMC-CEP-1347"). |
| `p_orb` | Float | Orbital period in days. |
| `p_puls` | Float | Pulsation period of the Cepheid in days. |
| `r2` | Float | Radius of the companion star (Star 2) in Solar Radii ($R_\odot$). |
| `color2` | String | Hex color code for the companion star (static). |
| `orbital_separation_rsun` | Float | Semi-major axis of the binary system in Solar Radii ($R_\odot$). |
| `inclination_deg` | Float | Orbital inclination in degrees (fixed at 57.0°). |
| `total_frames` | Integer | Total number of frames in the simulation arrays. |
| `dt` | Float | Time step between frames in days. |

---

### 2. `physics_frames`
Time-series arrays representing the **physically accurate** simulation. All arrays have a length equal to `total_frames`.

| Key | Type (Array) | Description |
| :--- | :--- | :--- |
| `t` | Float | Simulation time in days. |
| `x1`, `y1`, `z1` | Float | Cartesian coordinates of the Cepheid (Star 1) in Solar Radii. $Z$ represents depth for layering. |
| `x2`, `y2`, `z2` | Float | Cartesian coordinates of the Companion (Star 2) in Solar Radii. |
| `r1` | Float | Instantaneous radius of the Cepheid in Solar Radii (pulsating). |
| `color1` | String | Hex color of the Cepheid, varying with Temperature. |
| `v_mag` | Float | Instantaneous V-band magnitude (for UI text/graphs). |

---

### 3. `composite_frames`
Time-series arrays for the **"Composite/Cheat" mode**. In this mode, the pulsation frequency is artificially increased to show exactly 15 pulsation cycles per orbital revolution, allowing viewers to see the pulsation more clearly alongside the orbital motion.

| Key | Type (Array) | Description |
| :--- | :--- | :--- |
| `r1` | Float | Radius of the Cepheid in composite mode. |
| `color1` | String | Hex color of the Cepheid in composite mode. |
| `v_mag` | Float | V-band magnitude in composite mode. |

"""

# ==========================================
# EXECUTE DATA-DRIVEN ANIMATION
# ==========================================
#if popt_v is not None and popt_i is not None:
    #generate_data_driven_video(current_target, popt_v, popt_i, filename="cepheid_inclined_data.mp4", duration_days=current_target.p_orb, fps=30)

import matplotlib.animation as animation
from matplotlib.patches import Circle, Ellipse
import matplotlib.colors as mcolors
import numpy as np
import matplotlib.pyplot as plt

def generate_dashboard_video(target, df_v, popt_v, popt_i, filename="cepheid_dashboard_dynamic.mp4", duration_days=None, fps=30):
    print(f"🎬 Initializing Low-RAM Video Render for {target.name}...")

    a_tot, a1, a2 = calculate_orbital_elements(target)
    inclination_rad = np.radians(target.inclination_deg)

    # FORCE the DPI down to a web-friendly 100 so we don't render an 8K video
    fig, (ax_orbit, ax_lc) = plt.subplots(1, 2, figsize=(14, 6), facecolor='#111111', dpi=100)
    fig.patch.set_facecolor('#111111')

    # ... [Keep all the exact same drawing and setup code from Phase 4 here] ...

    # --- LEFT PANEL: ORBIT ---
    ax_orbit.set_facecolor('#111111')
    lim = a_tot * 1.2
    ax_orbit.set_xlim(-lim, lim)
    ax_orbit.set_ylim(-lim, lim)
    ax_orbit.set_aspect('equal')
    ax_orbit.axis('off')

    orbit1 = Ellipse((0, 0), width=a1*2, height=a1*2*np.cos(inclination_rad), color='white', fill=False, linestyle=':', alpha=0.3)
    orbit2 = Ellipse((0, 0), width=a2*2, height=a2*2*np.cos(inclination_rad), color='white', fill=False, linestyle=':', alpha=0.3)
    ax_orbit.add_patch(orbit1)
    ax_orbit.add_patch(orbit2)
    ax_orbit.plot(0, 0, marker='+', color='white', markersize=10, alpha=0.5)

    companion_color = teff_to_hex(target.teff2)
    star2 = Circle((0, 0), target.r2, color=companion_color, zorder=10)
    star1 = Circle((0, 0), target.r1, color='#ffffff', zorder=11)
    ax_orbit.add_patch(star2)
    ax_orbit.add_patch(star1)

    info_text = ax_orbit.text(0.05, 0.95, "", color='white', ha='left', va='top', transform=ax_orbit.transAxes, fontsize=12, fontfamily='monospace')

    # --- RIGHT PANEL: LIGHT CURVE ---
    ax_lc.set_facecolor('#111111')
    ax_lc.tick_params(colors='white')
    ax_lc.spines['bottom'].set_color('white')
    ax_lc.spines['top'].set_color('white')
    ax_lc.spines['right'].set_color('white')
    ax_lc.spines['left'].set_color('white')

    # NEW: X-axis represents relative phase around "now"
    ax_lc.set_xlim(-0.5, 0.5)

    # FIXED: Explicit Y-limits for the light curve so data doesn't disappear
    ax_lc.set_ylim(16, 18)

    ax_lc.set_xlabel("Relative Pulsation Phase (0 = Now)", color='white', fontsize=12)
    ax_lc.set_ylabel("V-band Magnitude", color='white', fontsize=12)
    ax_lc.set_title(f"{target.name} V-band Light Curve", color='white', fontsize=14)
    ax_lc.invert_yaxis()

    raw_phase = (df_v['BJD'] % target.p_puls) / target.p_puls

    # NEW: Initialize empty artists. We use `plot` with `.` instead of `errorbar`
    # because it is vastly easier to animate in real-time.
    raw_pts, = ax_lc.plot([], [], '.', color='gray', alpha=0.4, zorder=1, label="Raw Data")
    model_line, = ax_lc.plot([], [], color='#2ecc71', linewidth=2, zorder=2, label="Fourier Model")

    # NEW: The red dot and line stay permanently locked at x = 0
    lc_dot, = ax_lc.plot([0], [0], 'o', color='#e74c3c', markersize=10, zorder=4, markeredgecolor='white', markeredgewidth=1.5)
    lc_vline = ax_lc.axvline(x=0, color='#e74c3c', linestyle='--', alpha=0.5, zorder=3)

    ax_lc.legend(loc='upper right', facecolor='#222222', edgecolor='white', labelcolor='white')

    if duration_days is None:
        duration_days = target.p_orb
    frames = int(fps * duration_days)
    time_step = 1.0 / fps

    mean_mag_v = popt_v[0]
    radius_scale_factor = target.r1 * 0.2

    def update(frame):
        t = frame * time_step

        theta = 2 * np.pi * (t / target.p_orb)
        x1 = a1 * np.cos(theta)
        y1 = a1 * np.sin(theta) * np.cos(inclination_rad)
        star1.center = (x1, y1)

        x2 = a2 * np.cos(theta + np.pi)
        y2 = a2 * np.sin(theta + np.pi) * np.cos(inclination_rad)
        star2.center = (x2, y2)

        y1_true = a1 * np.sin(theta)
        if y1_true > 0:
            star1.set_zorder(9)
            star2.set_zorder(11)
        else:
            star1.set_zorder(11)
            star2.set_zorder(9)

        phase_puls = (t % target.p_puls) / target.p_puls
        mag_v = fourier_series(phase_puls, *popt_v)
        mag_i = fourier_series(phase_puls, *popt_i)

        v_minus_i = mag_v - mag_i
        current_teff = vi_index_to_teff(v_minus_i)
        star1.set_color(teff_to_hex(current_teff))

        delta_mag = mean_mag_v - mag_v
        current_r1 = target.r1 + (delta_mag * radius_scale_factor)
        star1.radius = current_r1

        # ==========================================
        # NEW: DYNAMIC TREADMILL GRAPH LOGIC
        # ==========================================

        # 1. Slide raw points left and wrap them cleanly between -0.5 and 0.5
        rel_phase = (raw_phase - phase_puls + 0.5) % 1.0 - 0.5
        raw_pts.set_data(rel_phase, df_v['Mag'])

        # 2. Shift the smooth model curve to match the new relative window
        x_smooth = np.linspace(-0.5, 0.5, 500)
        true_phases = (x_smooth + phase_puls) % 1.0
        smooth_mag = [fourier_series(p, *popt_v) for p in true_phases]
        model_line.set_data(x_smooth, smooth_mag)

        # 3. Update only the Y-position of the dot (X is locked at 0)
        lc_dot.set_data([0], [mag_v])

        info_str = (
            f"Time: {t:.1f} d\n"
            f"Puls Phase: {phase_puls:.2f}\n"
            f"V-Mag: {mag_v:.2f}\n"
            f"(V-I): {v_minus_i:.2f}\n"
            f"T_eff: ~{current_teff:.0f}K"
        )
        info_text.set_text(info_str)

        # NEW: Ensure you return the new artists so blit=True renders them!
        return star1, star2, info_text, orbit1, orbit2, raw_pts, model_line, lc_dot, lc_vline

    print(f"   ⏳ Streaming {frames} frames directly to disk via FFmpeg...")
    plt.tight_layout()
    anim = animation.FuncAnimation(fig, update, frames=frames, interval=1000/fps, blit=True)

    # NEW WRITER: FFmpeg streams directly to disk, using almost zero RAM!
    writer = animation.FFMpegWriter(fps=fps, bitrate=1800)
    anim.save(filename, writer=writer)

    print(f"✅ Saved full dashboard video to {filename}!")

    # CRITICAL: Close the figure to free up whatever RAM it did use
    plt.close(fig)

# ==========================================
# EXECUTE
# ==========================================
file_save_mp4 = 'CEP_1347_Animated.mp4'
file_save_gif = 'CEP_1347_Animated.gif'
if popt_v is not None and popt_i is not None:
    generate_dashboard_video(current_target, df_v, popt_v, popt_i, filename=f'{file_save_mp4}', duration_days=current_target.p_orb, fps=30)

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.animation as animation
import matplotlib.colors as mcolors
from matplotlib.patches import Circle, Ellipse
from matplotlib.gridspec import GridSpec

class CepheidSimulator:
    def __init__(self, target, popt_v, popt_i, df_v):
        """
        A unified physics engine for the Cepheid Binary System.

        Args:
            target (TargetConfig): The physical parameters of the system.
            popt_v (array): Fourier coefficients for V-band.
            popt_i (array): Fourier coefficients for I-band.
            df_v (DataFrame): Raw V-band data for the treadmill plot.
        """
        self.target = target
        self.popt_v = popt_v
        self.popt_i = popt_i
        self.df_v = df_v

        # Physics Constants
        self.INCLINATION = np.radians(target.inclination_deg)
        self.PHASE_SHIFT = 0.0 # Adjust to align model with data if needed

    @staticmethod
    def fourier_series(phase, a0, *args):
        """Vectorized Fourier series calculation."""
        result = np.full_like(phase, a0)
        n_harmonics = len(args) // 2
        for k in range(1, n_harmonics + 1):
            ak = args[2*(k-1)]
            bk = args[2*(k-1) + 1]
            # numpy broadcasting handles the arrays automatically
            result += ak * np.cos(2 * np.pi * k * phase) + bk * np.sin(2 * np.pi * k * phase)
        return result

    @staticmethod
    def teff_to_hex(teff):
        """
        Maps Teff to a physically accurate RGB hex color using a Blackbody lookup approximation.
        Data source: Mitchell Charity / Tanner Helland algorithms for sRGB.
        """
        # Clamping
        t = np.clip(teff, 1000, 40000)

        # Interpolated lookup table for speed and accuracy (Planckian Locus approximation)
        # Format: (Temp, R, G, B) normalized 0-1
        lookup_temps = np.array([1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000, 10000, 15000, 20000, 30000, 40000])
        lookup_colors = np.array([
            [1.0, 0.22, 0.0],   # 1000K (Very Red)
            [1.0, 0.55, 0.08],  # 2000K (Orange-Red)
            [1.0, 0.76, 0.45],  # 3000K (Warm Orange)
            [1.0, 0.90, 0.70],  # 4000K (Yellowish - The "Peach" zone)
            [1.0, 0.98, 0.92],  # 5000K (White-Yellow)
            [1.0, 1.0, 1.0],    # 6000K (Pure White)
            [0.9, 0.95, 1.0],   # 7000K (Cool White)
            [0.8, 0.9, 1.0],    # 8000K (Light Blue)
            [0.75, 0.85, 1.0],  # 9000K
            [0.70, 0.80, 1.0],  # 10000K (Blue)
            [0.60, 0.75, 1.0],  # 15000K
            [0.55, 0.70, 1.0],  # 20000K
            [0.50, 0.65, 1.0],  # 30000K
            [0.45, 0.60, 1.0]   # 40000K (Deep Blue)
        ])

        # Vectorized interpolation
        if np.isscalar(t):
            r = np.interp(t, lookup_temps, lookup_colors[:, 0])
            g = np.interp(t, lookup_temps, lookup_colors[:, 1])
            b = np.interp(t, lookup_temps, lookup_colors[:, 2])
            return mcolors.to_hex((r, g, b))
        else:
            # If input is array, return array of RGBs
            r = np.interp(t, lookup_temps, lookup_colors[:, 0])
            g = np.interp(t, lookup_temps, lookup_colors[:, 1])
            b = np.interp(t, lookup_temps, lookup_colors[:, 2])
            # Stack to get (N, 3)
            return np.stack([r, g, b], axis=1)

    def vi_to_teff(self, v_mag, i_mag):
        """Approximates Teff from V-I index."""
        vi = v_mag - i_mag
        # Empirical relation: Hotter (smaller V-I) -> Higher Teff
        # (V-I)=0.4 -> ~7500K, (V-I)=1.0 -> ~4500K
        return 9500 - 5000 * vi

    def precompute_physics(self, fps=30, duration_days=None):
        """
        Pre-calculates all physics frames before rendering.
        Returns a dictionary of arrays.
        """
        if duration_days is None:
            duration_days = self.target.p_orb

        n_frames = int(fps * duration_days)
        times = np.linspace(0, duration_days, n_frames)

        # 1. Orbital Kinematics
        theta = 2 * np.pi * (times / self.target.p_orb)

        # 2. Pulsation Physics
        puls_phase = (times % self.target.p_puls) / self.target.p_puls

        # 3. Photometry (Vectorized)
        mag_v = self.fourier_series(puls_phase, *self.popt_v)
        mag_i = self.fourier_series(puls_phase, *self.popt_i)

        # 4. Temperature & Color
        teff = self.vi_to_teff(mag_v, mag_i)

        # 5. Physical Radius (Stefan-Boltzmann: L ~ R^2 T^4)
        # R ~ sqrt(L) / T^2
        # log L ~ -0.4 * M_bol (approx M_v)
        # R_proportional ~ 10^(-0.2 * M_v) / T^2
        r_proxy = (10**(-0.2 * mag_v)) / (teff**2)
        # Normalize to the target's average radius
        radius_curve = self.target.r1 * (r_proxy / np.mean(r_proxy))

        return {
            'times': times,
            'theta': theta,
            'puls_phase': puls_phase,
            'mag_v': mag_v,
            'teff': teff,
            'radius': radius_curve,
            'n_frames': n_frames
        }

    def generate_video(self, filename="cepheid_website_palette.mp4", fps=30):
        print(f"🎬 Pre-computing physics for {self.target.name} (Website Style)...")
        data = self.precompute_physics(fps=fps)

        # --- PALETTE CONFIGURATION ---
        C_BG = '#ffffff'
        C_TEXT = '#111827'
        C_ORBIT = '#e5e7eb'
        C_GRID = '#9ca3af'
        C_COMPANION = '#2563eb'
        C_ACCENT = '#2563eb'
        C_RAW = '#9ca3af'
        C_INDICATOR = '#ef4444'

        # Calculate Orbit Geometry
        a_rsun, a1, a2 = 138.8, 49.7, 89.1
        # Recalculating efficiently
        P_sec = self.target.p_orb * 86400
        M_tot = (self.target.m1 + self.target.m2) * 1.989e30
        G = 6.674e-11
        a_m = ((G * M_tot * P_sec**2) / (4 * np.pi**2))**(1/3)
        a_rsun = a_m / 6.957e8
        a1 = a_rsun * (self.target.m2 / (self.target.m1 + self.target.m2))
        a2 = a_rsun * (self.target.m1 / (self.target.m1 + self.target.m2))

        # Setup Plot
        fig = plt.figure(figsize=(14, 6), facecolor=C_BG, dpi=100)
        gs = GridSpec(1, 2, figure=fig, width_ratios=[1, 1.2])
        ax_orb = fig.add_subplot(gs[0])
        ax_lc = fig.add_subplot(gs[1])

        # --- ORBIT SETUP ---
        ax_orb.set_facecolor(C_BG)
        # UPDATED ZOOM: Matching the user's test frame (0.8 instead of 1.1)
        lim = a_rsun * 0.8
        ax_orb.set_xlim(-lim, lim)
        ax_orb.set_ylim(-lim, lim)
        ax_orb.set_aspect('equal')
        ax_orb.axis('off')

        # Static Orbit Trails
        for r_orb in [a1, a2]:
            orbit = Ellipse((0, 0), width=r_orb*2, height=r_orb*2*np.cos(self.INCLINATION),
                            color=C_ORBIT, fill=False, linestyle='-', linewidth=1.5)
            ax_orb.add_patch(orbit)

        # Stars
        # Companion (Star 2) - Fixed Blue
        star2 = Circle((0, 0), self.target.r2, color=C_COMPANION, zorder=10)
        # Cepheid (Star 1) - Dynamic fill, dark edge for visibility on white
        star1 = Circle((0, 0), self.target.r1, facecolor='white', edgecolor=C_TEXT, linewidth=0.5, zorder=11)

        ax_orb.add_patch(star2)
        ax_orb.add_patch(star1)

        # Info Text
        info_text = ax_orb.text(0.05, 0.95, "Initializing...", color=C_TEXT,
                                transform=ax_orb.transAxes, fontsize=12, fontfamily='monospace', va='top')

        # --- LIGHT CURVE SETUP ---
        ax_lc.set_facecolor(C_BG)
        ax_lc.tick_params(axis='x', colors=C_TEXT)
        ax_lc.tick_params(axis='y', colors=C_TEXT)
        for spine in ax_lc.spines.values(): spine.set_color(C_GRID)

        ax_lc.set_xlim(-0.5, 0.5)
        ax_lc.set_ylim(data['mag_v'].max()+0.1, data['mag_v'].min()-0.1)
        ax_lc.set_xlabel("Phase (Relative)", color=C_TEXT)
        ax_lc.set_ylabel("V Magnitude", color=C_TEXT)
        ax_lc.set_title(f"{self.target.name} - V-Band", color=C_TEXT, loc='left')

        # Treadmill Artists
        raw_phase_static = (self.df_v['BJD'] % self.target.p_puls) / self.target.p_puls

        raw_points, = ax_lc.plot([], [], '.', color=C_RAW, alpha=0.5, markersize=4)
        model_line, = ax_lc.plot([], [], color=C_ACCENT, linewidth=2)
        indicator_dot, = ax_lc.plot([0], [0], 'o', color=C_INDICATOR, markersize=8, markeredgecolor='white')

        # Pre-calculate smooth model curve
        model_phase_x = np.linspace(0, 1, 200)

        def update(frame_idx):
            # Look up physics
            t = data['times'][frame_idx]
            theta = data['theta'][frame_idx]
            curr_puls_phase = data['puls_phase'][frame_idx]
            curr_mag = data['mag_v'][frame_idx]
            curr_r1 = data['radius'][frame_idx]
            curr_teff = data['teff'][frame_idx]

            # 1. Update Orbit Position
            x1 = a1 * np.cos(theta)
            y1 = a1 * np.sin(theta) * np.cos(self.INCLINATION)
            star1.center = (x1, y1)

            x2 = a2 * np.cos(theta + np.pi)
            y2 = a2 * np.sin(theta + np.pi) * np.cos(self.INCLINATION)
            star2.center = (x2, y2)

            # Z-Order
            y1_true = a1 * np.sin(theta)
            if y1_true > 0:
                star1.set_zorder(9)
                star2.set_zorder(11)
            else:
                star1.set_zorder(11)
                star2.set_zorder(9)

            # 2. Update Star Properties
            star1.radius = curr_r1
            # Note: We use set_facecolor so we don't overwrite the edge color
            star1.set_facecolor(self.teff_to_hex(curr_teff))

            # 3. Update Light Curve Treadmill
            shifted_phase = (raw_phase_static - curr_puls_phase + 0.5) % 1.0 - 0.5
            raw_points.set_data(shifted_phase, self.df_v['Mag'])

            window_x = np.linspace(-0.5, 0.5, 100)
            abs_phase_window = (window_x + curr_puls_phase) % 1.0
            window_y = self.fourier_series(abs_phase_window, *self.popt_v)
            model_line.set_data(window_x, window_y)

            # Indicator
            indicator_dot.set_data([0], [curr_mag])

            # Text
            info_str = (
                f"Epoch: {t:.1f} d\n"
                f"Phase: {curr_puls_phase:.2f}\n"
                f"Mag:   {curr_mag:.2f}\n"
                f"T_eff: {curr_teff:.0f} K"
            )
            info_text.set_text(info_str)

            return star1, star2, raw_points, model_line, indicator_dot, info_text

        print(f"   ⏳ Streaming {data['n_frames']} frames to disk...")
        anim = animation.FuncAnimation(fig, update, frames=data['n_frames'], interval=1000/fps, blit=True)

        writer = animation.FFMpegWriter(fps=fps, bitrate=2000)
        anim.save(filename, writer=writer)
        print(f"   ✅ Saved optimized video: {filename}")
        plt.close(fig)

# --- EXECUTION ---
# Ensure variables from previous cells exist
if 'popt_v' in globals() and 'popt_i' in globals():
    sim = CepheidSimulator(current_target, popt_v, popt_i, df_v)
    sim.generate_video("CEP_1347_Website.mp4", fps=30)
else:
    print("⚠️ Missing Fourier fits. Please run the fitting cell (Phase 2) first.")

import json
import numpy as np
import matplotlib.colors as mcolors

# Re-defining or Extending the Simulator to include JSON Export
class CepheidExporter(CepheidSimulator):
    def export_to_json(self, filename="master_data.json"):
        print(f"💾 Starting JSON Export for {self.target.name}...")

        # --- 1. Sampling Configuration ---
        # Requirement: P_puls sampled at least 120 times.
        samples_per_puls = 120
        # Total duration is exactly one orbital period
        duration = self.target.p_orb

        # Calculate time step dt
        dt = self.target.p_puls / samples_per_puls

        # Total frames for one full orbit
        n_frames = int(duration / dt)
        times = np.linspace(0, duration, n_frames)

        print(f"   • Time step: {dt:.5f} days")
        print(f"   • Total Frames: {n_frames}")

        # --- 2. Orbital Kinematics (Center-of-Mass) ---
        # Recalculate orbital elements (using stored logic)
        # Kepler's 3rd Law -> Semi-major axis
        P_sec = self.target.p_orb * 86400
        M_tot = (self.target.m1 + self.target.m2) * 1.989e30
        G = 6.674e-11
        a_m = ((G * M_tot * P_sec**2) / (4 * np.pi**2))**(1/3)
        a_rsun = a_m / 6.957e8

        # Distances from barycenter
        a1 = a_rsun * (self.target.m2 / (self.target.m1 + self.target.m2))
        a2 = a_rsun * (self.target.m1 / (self.target.m1 + self.target.m2))

        theta = 2 * np.pi * (times / self.target.p_orb)
        inclination = np.radians(self.target.inclination_deg)
        x1 = a1 * np.cos(theta)
        y1_raw = a1 * np.sin(theta)
        y1 = y1_raw * np.cos(inclination) # Visual Y
        z1 = y1_raw * np.sin(inclination) # Depth Z (for layering)

        # Star 2 (Companion)
        x2 = a2 * np.cos(theta + np.pi)
        y2_raw = a2 * np.sin(theta + np.pi)
        y2 = y2_raw * np.cos(inclination)
        z2 = y2_raw * np.sin(inclination)

        # --- 3. Real Physics Mode ---
        puls_phase_real = (times % self.target.p_puls) / self.target.p_puls

        # Vectorized Fourier Calculation
        mag_v_real = self.fourier_series(puls_phase_real, *self.popt_v)
        mag_i_real = self.fourier_series(puls_phase_real, *self.popt_i)

        # Teff & Color
        teff_real = self.vi_to_teff(mag_v_real, mag_i_real)

        # Convert Teff -> RGB Array -> Hex Strings
        rgb_real = self.teff_to_hex(teff_real)
        colors_hex_real = [mcolors.to_hex(c) for c in rgb_real]

        # Physical Radius (Relative Variation)
        # R ~ 10^(-0.2 * Mag) / T^2
        r_proxy = (10**(-0.2 * mag_v_real)) / (teff_real**2)
        r1_real = self.target.r1 * (r_proxy / np.mean(r_proxy))

        # --- 4. Composite Cheat Mode ---
        # Requirement: Exactly 15 cycles per orbit
        n_composite_cycles = 15
        composite_phase = (times / self.target.p_orb) * n_composite_cycles
        # Wrap phase 0-1 for Fourier input
        composite_phase_wrapped = composite_phase % 1.0

        # Recalculate Physics for Composite Mode
        mag_v_comp = self.fourier_series(composite_phase_wrapped, *self.popt_v)
        mag_i_comp = self.fourier_series(composite_phase_wrapped, *self.popt_i)

        teff_comp = self.vi_to_teff(mag_v_comp, mag_i_comp)
        rgb_comp = self.teff_to_hex(teff_comp)
        colors_hex_comp = [mcolors.to_hex(c) for c in rgb_comp]

        r_proxy_comp = (10**(-0.2 * mag_v_comp)) / (teff_comp**2)
        r1_comp = self.target.r1 * (r_proxy_comp / np.mean(r_proxy_comp))

        # --- 5. Construct JSON Structure ---
        output_data = {
            "metadata": {
                "name": self.target.name,
                "p_orb": self.target.p_orb,
                "p_puls": self.target.p_puls,
                "r2": self.target.r2,
                "color2": "#3b82f6", # Fixed website blue
                "orbital_separation_rsun": a_rsun,
                "inclination_deg": 57.0,
                "total_frames": n_frames,
                "dt": dt
            },
            "physics_frames": {
                "t": times.tolist(),
                "x1": x1.tolist(),
                "y1": y1.tolist(),
                "z1": z1.tolist(),
                "x2": x2.tolist(),
                "y2": y2.tolist(),
                "z2": z2.tolist(),
                "r1": r1_real.tolist(),
                "color1": colors_hex_real,
                "v_mag": mag_v_real.tolist()
            },
            "composite_frames": {
                "r1": r1_comp.tolist(),
                "v_mag": mag_v_comp.tolist(),
                "color1": colors_hex_comp
            }
        }

        # --- 6. Write to File ---
        with open(filename, 'w') as f:
            json.dump(output_data, f, indent=None) # Compact JSON (no indent)

        print(f"✅ Successfully exported {filename} ({len(json.dumps(output_data))/1024:.1f} KB)")
        return filename

# Execute Export
if 'popt_v' in globals() and 'popt_i' in globals():
    exporter = CepheidExporter(current_target, popt_v, popt_i, df_v)
    exporter.export_to_json("master_data2.json")
else:
    print("⚠️ Missing Fourier fits. Run Phase 2 first.")

import matplotlib.pyplot as plt
from matplotlib.patches import Circle, Ellipse
from matplotlib.gridspec import GridSpec
import numpy as np

def generate_test_frame(target, filename="test_frame_zoom.png"):
    print(f"📸 Generating Test Frame for {target.name}...")

    # --- PALETTE ---
    C_BG = '#ffffff'
    C_ORBIT = '#e5e7eb'
    C_COMPANION = '#2563eb'
    C_TEXT = '#111827'

    # --- GEOMETRY ---
    # Re-calculate geometry locally for the test frame
    P_sec = target.p_orb * 86400
    M_tot = (target.m1 + target.m2) * 1.989e30
    G = 6.674e-11
    a_m = ((G * M_tot * P_sec**2) / (4 * np.pi**2))**(1/3)
    a_rsun = a_m / 6.957e8
    a1 = a_rsun * (target.m2 / (target.m1 + target.m2))
    a2 = a_rsun * (target.m1 / (target.m1 + target.m2))

    inclination = np.radians(target.inclination_deg)
    fig = plt.figure(figsize=(8, 8), facecolor=C_BG, dpi=100)
    ax = fig.add_subplot(111)
    ax.set_facecolor(C_BG)

    # --- ZOOM SETTING IS HERE ---
    # We set the limit to 1.1x the semi-major axis
    lim = a_rsun * 0.8
    ax.set_xlim(-lim, lim)
    ax.set_ylim(-lim, lim)
    ax.set_aspect('equal')
    ax.axis('off')

    # Draw Orbits
    for r_orb in [a1, a2]:
        orbit = Ellipse((0, 0), width=r_orb*2, height=r_orb*2*np.cos(inclination),
                        color=C_ORBIT, fill=False, linestyle='-', linewidth=1.5)
        ax.add_patch(orbit)

    # Draw Stars (Arbitrary positions for test)
    # Star 1 at (a1, 0)
    x1 = a1
    y1 = 0
    star1 = Circle((x1, y1), target.r1, facecolor='white', edgecolor=C_TEXT, linewidth=0.5, zorder=11)

    # Star 2 at (-a2, 0)
    x2 = -a2
    y2 = 0
    star2 = Circle((x2, y2), target.r2, color=C_COMPANION, zorder=10)

    ax.add_patch(star1)
    ax.add_patch(star2)

    # Overlay Text to confirm Zoom
    ax.text(0, lim*0.9, f"Zoom Limit: {lim:.1f} R_sun", ha='center', color=C_TEXT)

    plt.savefig(filename, bbox_inches='tight')
    print(f"✅ Test frame saved to {filename}")
    plt.show()

# Execute
generate_test_frame(current_target)

!ffmpeg -i CEP_1347_Website.mp4 -vf "fps=30,scale=800:-1:flags=lanczos,split[s0][s1];[s0]palettegen[p];[s1][p]paletteuse" -loop 0 CEP-1347_Website.gif
